spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://175.196.226.213:3306/android_project?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root2
    password: root12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

